### ISSUE TITLE
5.8.0 ToDo

### ISSUE THREAD

**Issue by Delocuro** [Delocuro/Minestrapp-1.12#33]
### Features ###
- [ ] Finish Implementing Seed Bags
- [ ] Add Corpseweed
- [ ] Add Rock Crystal Decor
- [ ] Add Freezers
- [ ] Add Terraformerators
- [x] Add Quick Alloying Recipes (Block of Copper + Block of Tin = 3 Bronze Ingots, etc)
- [x] Add Sawmill JEI Support
- [ ] Re-Add Ritual Conduits
- [ ] Finish Soulsteel Vessel Functionality
- [ ] Add Siphons
- [ ] Finish Geode Functionality
- [ ] Add Heart Container Crafting
- [ ] Re-Add Mob Blocks
- [ ] Add Terracreep Genetics
- [ ] Re-Implement Basket Functionality?
- [ ] Re-Implement Redwood and Frozen Oak Trees
- [ ] Allow Tanning Indoors when Godstone is Adjacent
- [ ] Re-Add Flint Decor
- [x] Add Config for Adamantium Gen

### Bugs ###
- [ ] Fix Some of the Biome Redstone Bugs
- [ ] Sawmills Don't Display Blade until After Clicking Them upon Joining the World
- [ ] Sawmill Blade Doesn't Disappear After Breaking
- [x] Minesrapp Planks > Slabs Sawmill Recipes All Output Redwood Planks
- [ ] Heart Spot Config Disable Not Working?
- [x] Archantine Axe Attack Speed is Way too Slow
- [ ] Glow Glass Doesn't use Full-Block Model Type?
- [x] Infinite Glacieric Ice Shards Exploit
- [ ] Furnace/Alloy Furnace Z-Fighting Issues?
- [x] Palm Logs/Leaves not Flammable
- [x] Fix Activators not being breakable once placed.
- [x] Alloy Furnaces check the wrong input slot when deciding whether the desired Pipe input slot is full.
- [x] Palm Doors don't drop anything.
- [x] Sandy Desert Quartz Deposits don't drop anything if they try to drop Salt.
